services:
  backend:
    build: ./backend
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=5001
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - CLIENT_URL=http://localhost:5173

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"